Fixed issue on Xiaomi devices
Fixed the crashing outputtin the error:

D/testseb: Could not load zenroom native library: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.zencode-ya8XzFehNo-Wm20sxIpU2A==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.zencode-ya8XzFehNo-Wm20sxIpU2A==/lib/arm64, /system/lib64, /product/lib64]]] couldn't find "libzenroom.so"


05/20 09:54:28: Launching 'app' on Physical Device.
App restart successful without requiring a re-install.
$ adb shell am start -n "com.example.zencode/com.example.zencode.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 22761 on device 'xiaomi-m2007j17g-3e4ce50'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/Perf: Connecting to perf service.
I/FeatureParser: can't find gauguin.xml in assets/device_features/,it may be in /vendor/etc/device_features
E/libc: Access denied finding property "ro.vendor.df.effect.conflict"
    Access denied finding property "ro.vendor.knock.type"
D/testseb: Could not load zenroom native library: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.zencode-ya8XzFehNo-Wm20sxIpU2A==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.zencode-ya8XzFehNo-Wm20sxIpU2A==/lib/arm64, /system/lib64, /product/lib64]]] couldn't find "libzenroom.so"
D/testconsole: Executing Zenroom in verbose mode and printing the keypair only to console...
E/example.zencod: No implementation found for java.lang.String decode.zenroom.Zenroom.zenroom(java.lang.String, java.lang.String, java.lang.String, java.lang.String) (tried Java_decode_zenroom_Zenroom_zenroom and Java_decode_zenroom_Zenroom_zenroom__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.zencode, PID: 22761
    java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String decode.zenroom.Zenroom.zenroom(java.lang.String, java.lang.String, java.lang.String, java.lang.String) (tried Java_decode_zenroom_Zenroom_zenroom and Java_decode_zenroom_Zenroom_zenroom__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2)
        at decode.zenroom.Zenroom.zenroom(Native Method)
        at decode.zenroom.Zenroom.execute(Zenroom.java:34)
        at com.example.zencode.MainActivity.onCreate(MainActivity.java:43)
        at android.app.Activity.performCreate(Activity.java:7916)
        at android.app.Activity.performCreate(Activity.java:7903)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3288)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3462)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2049)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7574)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
I/Process: Sending signal. PID: 22761 SIG: 9